<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZdoLSxY\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZdoLSxY/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerZdoLSxY.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerZdoLSxY\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerZdoLSxY\App_KernelTestDebugContainer([
    'container.build_hash' => 'ZdoLSxY',
    'container.build_id' => '4876e25e',
    'container.build_time' => 1578583695,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZdoLSxY');
