<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'phone_index' => [[], ['_controller' => 'App\\Controller\\PhoneController::index'], [], [['text', '/phone/']], [], []],
    'phone_new' => [[], ['_controller' => 'App\\Controller\\PhoneController::new'], [], [['text', '/phone/new']], [], []],
    'phone_show' => [['id'], ['_controller' => 'App\\Controller\\PhoneController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/phone']], [], []],
    'phone_edit' => [['id'], ['_controller' => 'App\\Controller\\PhoneController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/phone']], [], []],
    'phone_delete' => [['id'], ['_controller' => 'App\\Controller\\PhoneController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/phone']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'share_delete' => [['id'], ['_controller' => 'App\\Controller\\ShareController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/share_delete']], [], []],
    'share' => [[], ['_controller' => 'App\\Controller\\ShareController::share'], [], [['text', '/share']], [], []],
    'homepage' => [[], ['template' => 'phonebook.html.twig', '_controller' => 'Symfony\\Bundle\\FrameworkBundle\\Controller\\TemplateController'], [], [['text', '/']], [], []],
];
